services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - /data/disk2t/jellyfin/config:/config
      - /data/jellyfin/cache:/cache
      - /data/disk4t/HomeCloud/Movies:/media/Movies:ro
      - /data/disk4t/HomeCloud/Shows:/media/Shows:ro
    restart: unless-stopped